### ISSUE TITLE
Problem with Postgresql

### ISSUE THREAD

**Issue by montymotz** [calvintam236/docker_miningcore#1]
Hello,

Maybe an idea?

Miningcore log says:

```
[2018-06-14 20:23:32.5273] [I] [dash1] [Pool] Launching ... 
[2018-06-14 20:23:32.5415] [I] [dash1] [Bitcoin Job Manager] Launching ... 
[2018-06-14 20:23:32.6067] [E] [PayoutManager] [dash1] Payment processing failed System.Net.Sockets.SocketException (111): Connection refused
at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
```

and

`[2018-06-14 14:18:19.0099] [I] [dash1] [Bitcoin Job Manager] Waiting for daemons to come online ...`

My Setup:

deamon start:
`./dashd -conf=/home/.dashcore/dash.conf -datadir=/home/.dashcore/`

deamon conf:
```
rpcuser=xxx
rpcpassword=xxx
rpcallowip=0.0.0.0/16
listen=1
server=1
daemon=1
maxconnections=64

```
Miningcore Start:
`docker run -v /home/miningcore:/miningcore -d --name calvin_miningcore -p 3062:3062 calvintam236/miningcore:x86_64 -c /miningcore/config.json`

Thanks in advanced.

**Comment by calvintam236** [comment]
This is not related to the docker image - please post your issue at [here](https://github.com/coinfoundry/miningcore).

PS: You need to attach your miningcore `config.json` as well.
